# Generated by Django 4.2.1 on 2023-05-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rallies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('level', models.CharField(choices=[('L1', 'Easy'), ('L2', 'Medium'), ('L3', 'Hard')], default='L2', max_length=10)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Participants_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.rallies')),
            ],
        ),
    ]
