# Generated by Django 4.2.1 on 2023-05-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_rallies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rallies',
            name='description',
            field=models.CharField(default='Lokalny rajd', max_length=50),
        ),
    ]
