# Generated by Django 4.2.1 on 2023-05-27 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0003_alter_rallies_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_rally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.rallies')),
            ],
        ),
        migrations.DeleteModel(
            name='Participants_List',
        ),
    ]
