# Generated by Django 4.2.1 on 2023-05-27 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0005_rides'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rallies',
            new_name='Rally',
        ),
        migrations.RenameModel(
            old_name='Rides',
            new_name='Ride',
        ),
    ]
