# Generated by Django 4.2.1 on 2023-06-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_delete_participantslist_delete_rally'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
