# Generated by Django 4.2.1 on 2023-05-28 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Lokalny rajd', max_length=50)),
                ('date', models.DateTimeField()),
                ('level', models.CharField(choices=[('L1', 'Easy'), ('L2', 'Medium'), ('L3', 'Hard')], default='L2', max_length=10)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_rally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rallies.rally')),
            ],
        ),
    ]
