# Generated by Django 4.2.1 on 2023-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rally',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='rally',
            name='date',
            field=models.DateField(),
        ),
    ]
