# Generated by Django 4.2.1 on 2023-06-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallies', '0003_ride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='distance',
        ),
        migrations.AddField(
            model_name='ride',
            name='max_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
