# Generated by Django 4.2.1 on 2023-06-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallies', '0004_remove_ride_distance_ride_max_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='total_time',
            field=models.FloatField(),
        ),
    ]
