# Generated by Django 4.2.1 on 2023-06-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallies', '0005_alter_ride_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='moving_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
