# Generated by Django 4.2.1 on 2023-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallies', '0006_ride_distance_ride_moving_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
